@startuml

skinparam backgroundColor #EEEBDC
skinparam handwritten true

skinparam sequence {
	ArrowColor DeepSkyBlue
	ActorBorderColor DeepSkyBlue
	LifeLineBorderColor blue
	LifeLineBackgroundColor #A9DCDF

	ParticipantBorderColor DeepSkyBlue
	ParticipantBackgroundColor DodgerBlue
	ParticipantFontName Impact
	ParticipantFontSize 17
	ParticipantFontColor #A9DCDF

	ActorBackgroundColor aqua
	ActorFontColor DeepSkyBlue
	ActorFontSize 17
	ActorFontName Aapex
}

autonumber

actor Actor as start
start -> XMLMapperBuilder: 解析mappers
    activate XMLMapperBuilder
    XMLMapperBuilder -> XMLMapperBuilder: parse
    XMLMapperBuilder -> XMLMapperBuilder: configurationElement
    XMLMapperBuilder -> XMLMapperBuilder: configurationElement


    deactivate XMLMapperBuilder
@enduml