@startuml
'https://plantuml.com/sequence-diagram


interface SqlSession
interface SqlSessionFactory
interface DisposableBean
class DefaultSqlSession {
}
class SqlSessionManager {
}
class SqlSessionTemplate {
}

SqlSession <|.. DefaultSqlSession
SqlSession <|.. SqlSessionManager
SqlSession <|.. SqlSessionTemplate
SqlSessionFactory <|.. SqlSessionManager
DisposableBean <|.. SqlSessionTemplate
@enduml